### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by nekulin** [TETYYS/LiveProxies#1]
LiveProxies/Interface.c:9:25: fatal error: SingleCheck.h: Нет такого файла или каталога
 #include "SingleCheck.h"

**Comment by TETYYS** [comment]
Oops! Didn't include Singlecheck.c / SingleCheck.h into project. Please note that Single proxy recheck doesn't work fully yet. You will be able to recheck SSL proxies if you will be connecting to interface through non-SSL port and you will be able only to recheck non-SSL proxies if you're connecting to interface through SSL port. This problem persists because of locking/threading issues and currently being fixed.
